# Quick intro to Python

In [1]:
a=5

In [2]:
type(a)

int

In [3]:
type(b)

NameError: name 'b' is not defined

In [4]:
b="five"

In [5]:
type(b)

str

In [6]:
c=5.0

In [11]:
for i in range(5):
    print("Hi",i)

Hi 0
Hi 1
Hi 2
Hi 3
Hi 4


In [12]:
def myadditon(a1,a2):
    return a1+a2

In [14]:
myadditon(1,2)

3

In [16]:
myadditon("a","b")

'ab'

In [17]:
def myaddition2(a1,a2=1.0):
     return a1+a2

In [18]:
myaddition2(1
           )

2.0

In [20]:
mylist=[1.0,2.0,3.0,4.0]

In [21]:
mylist[2]

3.0

In [24]:
mylist[-2]

3.0

In [25]:
len[mylist]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [26]:
len(mylist)

4

In [27]:
mylist.append(5.0)

In [28]:
mylist

[1.0, 2.0, 3.0, 4.0, 5.0]

In [29]:
mylist=mylist+[6.0]

In [30]:
mylist

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0]

In [38]:
mylist[1:1]

[]

In [39]:
mylist[:3]

[1.0, 2.0, 3.0]

In [40]:
mylist[:]

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0]

In [41]:
mylist[1:5]

[2.0, 3.0, 4.0, 5.0]

In [43]:
mylist=mylist+1.0

TypeError: can only concatenate list (not "float") to list

In [55]:
N =len(mylist);
for i in range(N):
        mylist[i]=mylist[i]+1.0

In [58]:

myarrray=numpy.arrary(mylist)

NameError: name 'numpy' is not defined

In [59]:
myarray=[1.0,2.0,3.0,4.0,5.0]

In [63]:
import numpy as np

In [65]:
x=np.arange(0.0,1.0,0.1)

In [66]:
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [69]:
x0=np.ones(10)

In [70]:
x0

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
y=x*x

In [72]:
y


array([0.  , 0.01, 0.04, 0.09, 0.16, 0.25, 0.36, 0.49, 0.64, 0.81])

In [73]:
y=x**2

In [74]:
y

array([0.  , 0.01, 0.04, 0.09, 0.16, 0.25, 0.36, 0.49, 0.64, 0.81])

In [75]:
from matplotlib import pyplot

In [76]:
%matplotlib inline

In [79]:
pyplot.figure()
pyplot.figure(x,y)

TypeError: only size-1 arrays can be converted to Python scalars

<Figure size 432x288 with 0 Axes>

In [80]:
pyplot.figure()
pyplot.figure(x,y)

TypeError: only size-1 arrays can be converted to Python scalars

<Figure size 432x288 with 0 Axes>

In [87]:
pyplot.figure(x,y)

TypeError: only size-1 arrays can be converted to Python scalars

In [88]:
a=np.array([1,2,3])

In [89]:
a

array([1, 2, 3])

In [90]:
b=a

In [91]:
a[0]+=1

In [92]:
a

array([2, 2, 3])

In [93]:
b

array([2, 2, 3])

In [95]:
b=a.copy()

In [96]:
a[0]+=1.0

In [97]:
b


array([2, 2, 3])

In [98]:
a

array([3, 2, 3])

In [99]:
a[0]+=1

In [100]:
a


array([4, 2, 3])

In [106]:
import math
t=np.arange(0,2*math.pi,0.01)

In [107]:
t

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09,
       1.1 , 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 ,
       1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31,
       1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42,
       1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.

In [109]:
theta=np.linspace(0.0,2*math.pi,num=25)

In [110]:
theta

array([0.        , 0.26179939, 0.52359878, 0.78539816, 1.04719755,
       1.30899694, 1.57079633, 1.83259571, 2.0943951 , 2.35619449,
       2.61799388, 2.87979327, 3.14159265, 3.40339204, 3.66519143,
       3.92699082, 4.1887902 , 4.45058959, 4.71238898, 4.97418837,
       5.23598776, 5.49778714, 5.75958653, 6.02138592, 6.28318531])

In [112]:
u=np.cos(theta)+2*np.sin(theta)+3

In [113]:
u

array([4.        , 4.48356392, 4.8660254 , 5.12132034, 5.23205081,
       5.1906707 , 5.        , 4.67303261, 4.23205081, 3.70710678,
       3.1339746 , 2.55171226, 2.        , 1.51643608, 1.1339746 ,
       0.87867966, 0.76794919, 0.8093293 , 1.        , 1.32696739,
       1.76794919, 2.29289322, 2.8660254 , 3.44828774, 4.        ])