In [1]:
from scipy import sparse
import numpy


In [2]:
def lhs_operator(N, sigma):
    row = numpy.zeros(N*3-2)
    for i in range(N):
        row[i]=i
    for i in range(N-1):
        row[N+i]=i
    for i in range(N-1):
        row[2*N-1+i]=i+1
    col = row.copy()
    for i in range(N-1):
        col[N+i]=i+1
    for i in range(N-1):
        col[2*N-1+i]=i
    data= numpy.ones(N*3-2)
    data = -data
    for i in range(N):
        data[i]=2+1/sigma
    data[N-1]=1+1/sigma
    c = sparse.coo_matrix((data,(row,col)),shape=(N,N))
    return c

In [8]:
c=lhs_operator(10,0.5)
c

<10x10 sparse matrix of type '<class 'numpy.float64'>'
	with 28 stored elements in COOrdinate format>

In [6]:
print (c.toarray())

[[ 4. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  4. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  4. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  4. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  4. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  4. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  4. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  4. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  4. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  3.]]


<10x10 sparse matrix of type '<class 'numpy.float64'>'
	with 28 stored elements in COOrdinate format>